name: Continuous integration

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install prerequisites
        run: |
          python -m pip install tox
      - name: Run tests
        run: |
          tox -e py37-tests
